events {
    worker_connections 1024;
}

http {
    server {
        listen 81;

        location / {
            root /home/la194lu/17349/nginx/3sitios/sitio1;
            index index.html;
        }
    }
}
